import { defineConfig, devices } from '@playwright/test';

// Phase B auth state — generated by e2e/global-setup.ts
const AUTH_STATE = './e2e/.auth/user.json';

export default defineConfig({
  testDir: './e2e',
  testMatch: '**/*.spec.ts',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,

  // Run global setup to authenticate test user before Phase B tests
  globalSetup: './e2e/global-setup.ts',

  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/e2e-results.json' }],
    ['junit', { outputFile: 'test-results/junit.xml' }],
  ],
  use: {
    baseURL: process.env.BASE_URL || 'https://www.selfprint.one',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    // Phase A — production smoke tests (no auth required)
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      testMatch: ['**/smoke.spec.ts', '**/auth.spec.ts', '**/critical-journey.spec.ts'],
    },
    // Phase B — staging integration tests (requires auth + seeded DB)
    {
      name: 'chromium-staging',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.STAGING_URL || 'https://staging.selfprint.one',
        storageState: AUTH_STATE,
      },
      testMatch: [
        '**/twin.spec.ts',
        '**/decision.spec.ts',
        '**/upload.spec.ts',
        '**/world-visual.spec.ts',
        '**/lifecycle.spec.ts',
      ],
    },
    // Mobile — Phase A only
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
      testMatch: ['**/smoke.spec.ts'],
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
      testMatch: ['**/smoke.spec.ts'],
    },
  ],
  webServer: undefined,
  timeout: 180000,
  expect: { timeout: 20000 },
  globalTimeout: 15 * 60 * 1000,
});
