import { defineConfig, devices } from '@playwright/test';
import { existsSync } from 'fs';

// Phase B auth state — generated by e2e/global-setup.ts
// PLAYWRIGHTCFG-001 (6 Sep 2026): file lives outside git (.gitignore).
// CI skips Phase B when it doesn't exist — no ENOENT crash.
const AUTH_STATE = './e2e/.auth/user.json';
const hasAuthState = existsSync(AUTH_STATE);

export default defineConfig({
  testDir: './e2e',
  testMatch: '**/*.spec.ts',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,

  // Run global setup to authenticate test user before Phase B tests
  globalSetup: './e2e/global-setup.ts',

  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/e2e-results.json' }],
    ['junit', { outputFile: 'test-results/junit.xml' }],
  ],
  use: {
    baseURL: process.env.BASE_URL || 'https://www.selfprint.one',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    // Phase A — production smoke tests (no auth required)
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      testMatch: ['**/smoke.spec.ts', '**/auth.spec.ts', '**/critical-journey.spec.ts'],
    },
    // Phase B — staging integration tests (requires auth + seeded DB)
    // Only runs when e2e/.auth/user.json exists (generated by global-setup.ts
    // when E2E_SUPABASE_URL + E2E_SUPABASE_ANON_KEY are set). Skipped in CI
    // that only sets production smoke test secrets. (PLAYWRIGHTCFG-001)
    ...(hasAuthState ? [{
      name: 'chromium-staging',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.STAGING_URL || 'https://staging.selfprint.one',
        storageState: AUTH_STATE,
      },
      testMatch: [
        '**/twin.spec.ts',
        '**/decision.spec.ts',
        '**/upload.spec.ts',
        '**/world-visual.spec.ts',
        '**/lifecycle.spec.ts',
      ],
    }] : []),
    // Mobile — Phase A only
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
      testMatch: ['**/smoke.spec.ts'],
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
      testMatch: ['**/smoke.spec.ts'],
    },
  ],
  webServer: undefined,
  timeout: 180000, // 3 minutes per test (Twin creation needs SICE + DB)
  expect: { timeout: 20000 },
  globalTimeout: 25 * 60 * 1000,
});
