import { defineConfig, devices } from '@playwright/test';

// Phase B auth state — generated by e2e/global-setup.ts.
// PLAYWRIGHTCFG-002 (12 Sep 2026): file lives outside git (.gitignore).
// chromium-staging is defined UNCONDITIONALLY so project selection is
// deterministic at config-evaluation time — there is no existsSync race
// with globalSetup (PLAYWRIGHTCFG-001 removed). e2e/global-setup.ts is the
// single source of truth for the storage state file:
//   - credentials present  → authenticates and saves the real session
//   - credentials absent   → explicit staging run fails with a clear error;
//                            Phase A-only run writes a logged-out placeholder
//                            so the project index stays stable either way.
const AUTH_STATE = './e2e/.auth/user.json';

export default defineConfig({
  testDir: './e2e',
  testMatch: '**/*.spec.ts',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,

  // Run global setup to authenticate test user before Phase B tests
  globalSetup: './e2e/global-setup.ts',

  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/e2e-results.json' }],
    ['junit', { outputFile: 'test-results/junit.xml' }],
  ],
  use: {
    baseURL: process.env.BASE_URL || 'https://www.selfprint.one',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    // Phase A — production smoke tests (no auth required)
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      testMatch: ['**/smoke.spec.ts', '**/auth.spec.ts', '**/critical-journey.spec.ts'],
    },
    // Phase B — staging integration tests (requires auth + seeded DB).
    // Defined unconditionally (PLAYWRIGHTCFG-002). Selection is decoupled
    // from the storage state file's existence:
    //   * E2E creds set  → global-setup.ts authenticates and creates the file
    //   * E2E creds unset → global-setup.ts fails a staging run clearly, or
    //     writes a logged-out placeholder for Phase A-only runs.
    {
      name: 'chromium-staging',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.STAGING_URL || 'https://selfprint-staging.pages.dev',
        storageState: AUTH_STATE,
      },
      testMatch: [
        '**/twin.spec.ts',
        '**/decision.spec.ts',
        '**/upload.spec.ts',
        '**/world-visual.spec.ts',
        '**/lifecycle.spec.ts',
        '**/master-gate.spec.ts',
      ],
    },
    // Mobile — Phase A only
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
      testMatch: ['**/smoke.spec.ts'],
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
      testMatch: ['**/smoke.spec.ts'],
    },
  ],
  webServer: undefined,
  timeout: 180000, // 3 minutes per test (Twin creation needs SICE + DB)
  expect: { timeout: 20000 },
  globalTimeout: 25 * 60 * 1000,
});