/**
 * badges.ts
 * World-specific badges and achievements (P0 #7.4)
 */

import type { WorldId } from '../constants/worlds';

export type BadgeRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic';

export interface Badge {
  id: string;
  worldId: WorldId;
  name: string;
  icon: string;
  description: string;
  rarity: BadgeRarity;
  criteria: string; // What user must do to unlock
  unlockedAt?: string; // ISO timestamp
  progress?: number; // 0-100 for partial progress
}

export interface WorldAchievement {
  worldId: WorldId;
  achievementId: string;
  name: string;
  description: string;
  icon: string;
  points: number; // XP for this achievement
  unlockedAt?: string;
}

/**
 * World-specific badge definitions
 */
export const WORLD_BADGES: Record<WorldId, Badge[]> = {
  self: [
    {
      id: 'self-awakening',
      worldId: 'self',
      name: 'Self Awakening',
      icon: '🌅',
      description: 'Complete your first self-discovery journal entry',
      rarity: 'common',
      criteria: 'Write 1 entry in Self world',
    },
    {
      id: 'self-introspection',
      worldId: 'self',
      name: 'Introspection Beginner',
      icon: '🤔',
      description: 'Write 3 self-reflection entries',
      rarity: 'common',
      criteria: 'Write 3 entries about yourself',
    },
    {
      id: 'self-authentic',
      worldId: 'self',
      name: 'Authentic Self',
      icon: '💎',
      description: 'Identify 3 core values',
      rarity: 'uncommon',
      criteria: 'Articulate personal values',
    },
    {
      id: 'self-aligned',
      worldId: 'self',
      name: 'Values Aligned',
      icon: '✨',
      description: 'Make 5 decisions aligned with values',
      rarity: 'uncommon',
      criteria: 'Track 5 value-aligned decisions',
    },
    {
      id: 'self-mirror-master',
      worldId: 'self',
      name: 'Mirror Master',
      icon: '🪞',
      description: 'Complete 10 self-reflection entries',
      rarity: 'rare',
      criteria: 'Write 10 entries in Self world',
    },
    {
      id: 'self-shadow-work',
      worldId: 'self',
      name: 'Shadow Worker',
      icon: '🌙',
      description: 'Explore 5 shadow aspects of yourself',
      rarity: 'rare',
      criteria: 'Journal about personal shadows',
    },
    {
      id: 'self-mastery',
      worldId: 'self',
      name: 'Self Mastery',
      icon: '👑',
      description: 'Maintain consistent self-work for 60 days',
      rarity: 'epic',
      criteria: 'Journal consistently for 2 months',
    },
    {
      id: 'self-integrated',
      worldId: 'self',
      name: 'Integrated Self',
      icon: '🎭',
      description: 'Balance all aspects of your personality',
      rarity: 'epic',
      criteria: 'Show harmony in 3+ life areas',
    },
    {
      id: 'self-enlightenment',
      worldId: 'self',
      name: 'Self-Enlightenment',
      icon: '🔆',
      description: 'Achieve profound self-understanding',
      rarity: 'legendary',
      criteria: 'Complete 50+ self entries',
    },
    {
      id: 'self-transcendence',
      worldId: 'self',
      name: 'Transcended Ego',
      icon: '🌟',
      description: 'Transcend limiting self-beliefs',
      rarity: 'legendary',
      criteria: 'Transform 3+ core beliefs',
    },
    {
      id: 'self-destiny',
      worldId: 'self',
      name: 'Destiny Creator',
      icon: '⚡',
      description: 'Align fully with your authentic purpose',
      rarity: 'mythic',
      criteria: 'Live your values for 90+ days',
    },
    {
      id: 'self-awakened-master',
      worldId: 'self',
      name: 'Awakened Master',
      icon: '👁️',
      description: 'Become the fullest expression of yourself',
      rarity: 'mythic',
      criteria: 'Achieve complete self-actualization',
    },
  ],
  mind: [
    {
      id: 'mind-clarity',
      worldId: 'mind',
      name: 'Mental Clarity',
      icon: '☀️',
      description: 'Track emotional state for 7 days',
      rarity: 'common',
      criteria: 'Log emotions daily for 1 week',
    },
    {
      id: 'mind-observer',
      worldId: 'mind',
      name: 'Mindful Observer',
      icon: '👁️',
      description: 'Become aware of your thought patterns',
      rarity: 'common',
      criteria: 'Journal about thoughts 5 times',
    },
    {
      id: 'mind-focus',
      worldId: 'mind',
      name: 'Focus Master',
      icon: '🎯',
      description: 'Complete 5 focus-related decisions',
      rarity: 'uncommon',
      criteria: 'Make 5 decisions about mental focus',
    },
    {
      id: 'mind-resilient',
      worldId: 'mind',
      name: 'Mental Resilience',
      icon: '💪',
      description: 'Navigate 5 challenging thoughts',
      rarity: 'uncommon',
      criteria: 'Process difficult emotions',
    },
    {
      id: 'mind-breakthrough',
      worldId: 'mind',
      name: 'Breakthrough Maker',
      icon: '🔓',
      description: 'Experience a mental breakthrough',
      rarity: 'rare',
      criteria: 'Resolve 3+ limiting beliefs',
    },
    {
      id: 'mind-flow',
      worldId: 'mind',
      name: 'Flow State Master',
      icon: '🌊',
      description: 'Achieve flow state regularly',
      rarity: 'rare',
      criteria: 'Experience flow 10+ times',
    },
    {
      id: 'mind-emotional-intelligence',
      worldId: 'mind',
      name: 'Emotional Intelligence',
      icon: '❤️',
      description: 'Master emotional awareness',
      rarity: 'epic',
      criteria: 'Track emotions for 30+ days',
    },
    {
      id: 'mind-peace',
      worldId: 'mind',
      name: 'Inner Peace',
      icon: '🕉️',
      description: 'Maintain inner calm for 30 days',
      rarity: 'epic',
      criteria: 'Stay emotionally balanced',
    },
    {
      id: 'mind-enlightenment',
      worldId: 'mind',
      name: 'Mental Enlightenment',
      icon: '✨',
      description: 'Achieve perfect emotional balance',
      rarity: 'legendary',
      criteria: 'Maintain balanced emotions for 90 days',
    },
    {
      id: 'mind-mastery',
      worldId: 'mind',
      name: 'Mind Master',
      icon: '🧠',
      description: 'Full command over your thoughts',
      rarity: 'legendary',
      criteria: 'Master your mental processes',
    },
    {
      id: 'mind-cosmic-consciousness',
      worldId: 'mind',
      name: 'Cosmic Consciousness',
      icon: '🌌',
      description: 'Connect to higher consciousness',
      rarity: 'mythic',
      criteria: 'Experience unity consciousness',
    },
    {
      id: 'mind-enlightened-sage',
      worldId: 'mind',
      name: 'Enlightened Sage',
      icon: '🧙‍♂️',
      description: 'Become a beacon of wisdom',
      rarity: 'mythic',
      criteria: 'Integrate all mental lessons',
    },
  ],
  relationship: [
    {
      id: 'relationship-connector',
      worldId: 'relationship',
      name: 'Connector',
      icon: '🌉',
      description: 'Identify one key relationship to strengthen',
      rarity: 'common',
      criteria: 'Journal about relationships once',
    },
    {
      id: 'relationship-listener',
      worldId: 'relationship',
      name: 'Active Listener',
      icon: '👂',
      description: 'Listen deeply to others',
      rarity: 'common',
      criteria: 'Practice active listening 5 times',
    },
    {
      id: 'relationship-communicator',
      worldId: 'relationship',
      name: 'Communicator',
      icon: '💬',
      description: 'Make 3 communication-related decisions',
      rarity: 'uncommon',
      criteria: 'Track 3 relationship decisions',
    },
    {
      id: 'relationship-empathetic',
      worldId: 'relationship',
      name: 'Empathetic Heart',
      icon: '🫂',
      description: 'Develop emotional empathy',
      rarity: 'uncommon',
      criteria: 'Understand others deeply 5+ times',
    },
    {
      id: 'relationship-vulnerable-heart',
      worldId: 'relationship',
      name: 'Vulnerable Heart',
      icon: '💔',
      description: 'Express vulnerability openly',
      rarity: 'rare',
      criteria: 'Share vulnerable moments with others',
    },
    {
      id: 'relationship-intimate-bond',
      worldId: 'relationship',
      name: 'Intimate Connector',
      icon: '💕',
      description: 'Deepen emotional intimacy',
      rarity: 'rare',
      criteria: 'Build 3 intimate relationships',
    },
    {
      id: 'relationship-authentic-connection',
      worldId: 'relationship',
      name: 'Authentic Presence',
      icon: '✨',
      description: 'Create authentic connections',
      rarity: 'epic',
      criteria: 'Be fully present in relationships',
    },
    {
      id: 'relationship-soulmate-ready',
      worldId: 'relationship',
      name: 'Soulmate Ready',
      icon: '💑',
      description: 'Prepare for deep partnership',
      rarity: 'epic',
      criteria: 'Complete relationship self-work',
    },
    {
      id: 'relationship-union',
      worldId: 'relationship',
      name: 'Sacred Union',
      icon: '🌺',
      description: 'Achieve true partnership',
      rarity: 'legendary',
      criteria: 'Create lasting partnership',
    },
    {
      id: 'relationship-transcendent-love',
      worldId: 'relationship',
      name: 'Transcendent Love',
      icon: '🌟',
      description: 'Experience transcendent connection',
      rarity: 'legendary',
      criteria: 'Merge with another fully',
    },
    {
      id: 'relationship-divine-bond',
      worldId: 'relationship',
      name: 'Divine Bond',
      icon: '🙏',
      description: 'Connect beyond ego',
      rarity: 'mythic',
      criteria: 'Transcend individual boundaries',
    },
    {
      id: 'relationship-enlightened-partner',
      worldId: 'relationship',
      name: 'Enlightened Partner',
      icon: '👁️',
      description: 'Become beacon in relationships',
      rarity: 'mythic',
      criteria: 'Inspire others through love',
    },
  ],
  love: [
    {
      id: 'love-open-heart',
      worldId: 'love',
      name: 'Open Heart',
      icon: '💖',
      description: 'Write your first love reflection',
      rarity: 'common',
      criteria: 'Journal about love once',
    },
    {
      id: 'love-courageous',
      worldId: 'love',
      name: 'Courageous Lover',
      icon: '🦁',
      description: 'Express your feelings openly',
      rarity: 'common',
      criteria: 'Communicate vulnerability',
    },
    {
      id: 'love-vulnerable',
      worldId: 'love',
      name: 'Vulnerability Bearer',
      icon: '🌹',
      description: 'Share 5 vulnerable moments',
      rarity: 'uncommon',
      criteria: 'Make 5 entries about vulnerability',
    },
    {
      id: 'love-intimate',
      worldId: 'love',
      name: 'Intimate Connector',
      icon: '🤗',
      description: 'Deepen emotional connections',
      rarity: 'uncommon',
      criteria: 'Build intimate relationships',
    },
    {
      id: 'love-authentic',
      worldId: 'love',
      name: 'Authentic Lover',
      icon: '💫',
      description: 'Love without conditions',
      rarity: 'rare',
      criteria: 'Practice unconditional love',
    },
    {
      id: 'love-passionate',
      worldId: 'love',
      name: 'Passionate Heart',
      icon: '🔥',
      description: 'Experience deep romantic passion',
      rarity: 'rare',
      criteria: 'Embrace your passion',
    },
    {
      id: 'love-giving',
      worldId: 'love',
      name: 'Generous Lover',
      icon: '🎁',
      description: 'Master the art of loving',
      rarity: 'epic',
      criteria: 'Show consistent love',
    },
    {
      id: 'love-receiving',
      worldId: 'love',
      name: 'Worthy Beloved',
      icon: '👑',
      description: 'Fully receive love from others',
      rarity: 'epic',
      criteria: 'Accept love gracefully',
    },
    {
      id: 'love-transcendent',
      worldId: 'love',
      name: 'Transcendent Love',
      icon: '✨',
      description: 'Experience divine love connection',
      rarity: 'legendary',
      criteria: 'Merge love with spirituality',
    },
    {
      id: 'love-soulmate',
      worldId: 'love',
      name: 'Soulmate Union',
      icon: '💑',
      description: 'Create a soulmate partnership',
      rarity: 'legendary',
      criteria: 'Find and nurture deep connection',
    },
    {
      id: 'love-universal',
      worldId: 'love',
      name: 'Universal Love',
      icon: '🌍',
      description: 'Extend love to all beings',
      rarity: 'mythic',
      criteria: 'Love humanity fully',
    },
    {
      id: 'love-enlightened',
      worldId: 'love',
      name: 'Enlightened Heart',
      icon: '🌟',
      description: 'Become love incarnate',
      rarity: 'mythic',
      criteria: 'Live as pure love',
    },
  ],
  career: [
    {
      id: 'career-purpose-finder',
      worldId: 'career',
      name: 'Purpose Finder',
      icon: '🎯',
      description: 'Define your professional purpose',
      rarity: 'common',
      criteria: 'Write about career purpose',
    },
    {
      id: 'career-pathfinder',
      worldId: 'career',
      name: 'Career Pathfinder',
      icon: '🛤️',
      description: 'Map your career direction',
      rarity: 'common',
      criteria: 'Plan career progression',
    },
    {
      id: 'career-leader',
      worldId: 'career',
      name: 'Leader',
      icon: '👑',
      description: 'Make 5 leadership-related decisions',
      rarity: 'uncommon',
      criteria: 'Track 5 leadership decisions',
    },
    {
      id: 'career-visionary',
      worldId: 'career',
      name: 'Career Visionary',
      icon: '🔭',
      description: 'Envision your career legacy',
      rarity: 'uncommon',
      criteria: 'Create your career vision',
    },
    {
      id: 'career-impact-maker',
      worldId: 'career',
      name: 'Impact Maker',
      icon: '💥',
      description: 'Create meaningful work impact',
      rarity: 'rare',
      criteria: 'Make 5+ career impact decisions',
    },
    {
      id: 'career-expert',
      worldId: 'career',
      name: 'Expert',
      icon: '🎓',
      description: 'Develop deep expertise',
      rarity: 'rare',
      criteria: 'Master your craft',
    },
    {
      id: 'career-master-craft',
      worldId: 'career',
      name: 'Master Craftsperson',
      icon: '🏆',
      description: 'Perfect your professional skills',
      rarity: 'epic',
      criteria: 'Achieve professional excellence',
    },
    {
      id: 'career-aligned-purpose',
      worldId: 'career',
      name: 'Purpose Aligned',
      icon: '✨',
      description: 'Align career with life purpose',
      rarity: 'epic',
      criteria: 'Live your professional calling',
    },
    {
      id: 'career-legacy-builder',
      worldId: 'career',
      name: 'Legacy Builder',
      icon: '🏛️',
      description: 'Create lasting career legacy',
      rarity: 'legendary',
      criteria: 'Build enduring impact',
    },
    {
      id: 'career-world-changer',
      worldId: 'career',
      name: 'World Changer',
      icon: '🌍',
      description: 'Change your industry',
      rarity: 'legendary',
      criteria: 'Transform your field',
    },
    {
      id: 'career-destiny-fulfiller',
      worldId: 'career',
      name: 'Destiny Fulfiller',
      icon: '⚡',
      description: 'Fulfill your professional destiny',
      rarity: 'mythic',
      criteria: 'Achieve ultimate career fulfillment',
    },
    {
      id: 'career-enlightened-guide',
      worldId: 'career',
      name: 'Enlightened Guide',
      icon: '🧙',
      description: 'Guide others to greatness',
      rarity: 'mythic',
      criteria: 'Mentor and inspire',
    },
  ],
  wealth: [
    {
      id: 'wealth-abundance-mindset',
      worldId: 'wealth',
      name: 'Abundance Mindset',
      icon: '🌟',
      description: 'Shift your money beliefs',
      rarity: 'common',
      criteria: 'Journal about wealth once',
    },
    {
      id: 'wealth-abundance-seeker',
      worldId: 'wealth',
      name: 'Abundance Seeker',
      icon: '🔍',
      description: 'Identify wealth opportunities',
      rarity: 'common',
      criteria: 'Recognize 5 abundance opportunities',
    },
    {
      id: 'wealth-strategist',
      worldId: 'wealth',
      name: 'Wealth Strategist',
      icon: '📊',
      description: 'Make 5 financial decisions',
      rarity: 'uncommon',
      criteria: 'Track 5 wealth decisions',
    },
    {
      id: 'wealth-investor',
      worldId: 'wealth',
      name: 'Wise Investor',
      icon: '💰',
      description: 'Build wealth through investment',
      rarity: 'uncommon',
      criteria: 'Make smart investment moves',
    },
    {
      id: 'wealth-prosperity-creator',
      worldId: 'wealth',
      name: 'Prosperity Creator',
      icon: '🌱',
      description: 'Generate multiple income streams',
      rarity: 'rare',
      criteria: 'Create wealth pathways',
    },
    {
      id: 'wealth-abundance-generator',
      worldId: 'wealth',
      name: 'Abundance Generator',
      icon: '✨',
      description: 'Manifest abundance consistently',
      rarity: 'rare',
      criteria: 'Attract continuous prosperity',
    },
    {
      id: 'wealth-financial-master',
      worldId: 'wealth',
      name: 'Financial Master',
      icon: '👑',
      description: 'Master wealth creation',
      rarity: 'epic',
      criteria: 'Achieve financial excellence',
    },
    {
      id: 'wealth-generosity-champion',
      worldId: 'wealth',
      name: 'Generosity Champion',
      icon: '🤝',
      description: 'Give abundantly to others',
      rarity: 'epic',
      criteria: 'Practice conscious giving',
    },
    {
      id: 'wealth-universal-prosperity',
      worldId: 'wealth',
      name: 'Universal Prosperity',
      icon: '🌌',
      description: 'Create wealth for all',
      rarity: 'legendary',
      criteria: 'Share abundance widely',
    },
    {
      id: 'wealth-abundance-incarnate',
      worldId: 'wealth',
      name: 'Abundance Incarnate',
      icon: '💎',
      description: 'Become abundance itself',
      rarity: 'legendary',
      criteria: 'Embody prosperity',
    },
    {
      id: 'wealth-cosmic-abundance',
      worldId: 'wealth',
      name: 'Cosmic Abundance',
      icon: '🌟',
      description: 'Connect to infinite wealth',
      rarity: 'mythic',
      criteria: 'Access universal prosperity',
    },
    {
      id: 'wealth-enlightened-benefactor',
      worldId: 'wealth',
      name: 'Enlightened Benefactor',
      icon: '🙏',
      description: 'Bless others with wealth',
      rarity: 'mythic',
      criteria: 'Transform lives through generosity',
    },
  ],
  life: [
    {
      id: 'life-adventurer',
      worldId: 'life',
      name: 'Adventurer',
      icon: '🗺️',
      description: 'Plan your first life adventure',
      rarity: 'common',
      criteria: 'Journal about life experiences',
    },
    {
      id: 'life-explorer',
      worldId: 'life',
      name: 'Life Explorer',
      icon: '🧭',
      description: 'Explore new life possibilities',
      rarity: 'common',
      criteria: 'Try 3 new experiences',
    },
    {
      id: 'life-balanced',
      worldId: 'life',
      name: 'Balanced',
      icon: '⚖️',
      description: 'Achieve life-work balance',
      rarity: 'uncommon',
      criteria: 'Make 3 balance-related decisions',
    },
    {
      id: 'life-harmony-seeker',
      worldId: 'life',
      name: 'Harmony Seeker',
      icon: '🎼',
      description: 'Create life harmony',
      rarity: 'uncommon',
      criteria: 'Balance all life areas',
    },
    {
      id: 'life-vitality-master',
      worldId: 'life',
      name: 'Vitality Master',
      icon: '💥',
      description: 'Radiate life energy',
      rarity: 'rare',
      criteria: 'Maintain vibrant energy',
    },
    {
      id: 'life-joy-cultivator',
      worldId: 'life',
      name: 'Joy Cultivator',
      icon: '😄',
      description: 'Cultivate daily joy',
      rarity: 'rare',
      criteria: 'Practice gratitude & joy',
    },
    {
      id: 'life-fulfillment-creator',
      worldId: 'life',
      name: 'Fulfillment Creator',
      icon: '🌺',
      description: 'Create life fulfillment',
      rarity: 'epic',
      criteria: 'Build meaningful life',
    },
    {
      id: 'life-living-fully',
      worldId: 'life',
      name: 'Living Fully',
      icon: '✨',
      description: 'Live with full aliveness',
      rarity: 'epic',
      criteria: 'Embrace life completely',
    },
    {
      id: 'life-mastery',
      worldId: 'life',
      name: 'Life Mastery',
      icon: '🏆',
      description: 'Master the art of living',
      rarity: 'legendary',
      criteria: 'Achieve life excellence',
    },
    {
      id: 'life-thriving-excellence',
      worldId: 'life',
      name: 'Thriving Excellence',
      icon: '👑',
      description: 'Thrive beyond survival',
      rarity: 'legendary',
      criteria: 'Reach peak life experience',
    },
    {
      id: 'life-enlightened-living',
      worldId: 'life',
      name: 'Enlightened Living',
      icon: '🌟',
      description: 'Live with full consciousness',
      rarity: 'mythic',
      criteria: 'Transcend ordinary existence',
    },
    {
      id: 'life-cosmic-consciousness',
      worldId: 'life',
      name: 'Cosmic Consciousness',
      icon: '🌌',
      description: 'Connect to cosmic existence',
      rarity: 'mythic',
      criteria: 'Experience unity with all',
    },
  ],
  growth: [
    {
      id: 'growth-learner',
      worldId: 'growth',
      name: 'Lifelong Learner',
      icon: '📚',
      description: 'Identify 3 growth areas',
      rarity: 'common',
      criteria: 'Journal about personal growth',
    },
    {
      id: 'growth-curious',
      worldId: 'growth',
      name: 'Curious Explorer',
      icon: '🔬',
      description: 'Embrace curiosity deeply',
      rarity: 'common',
      criteria: 'Explore 5 new topics',
    },
    {
      id: 'growth-progressive',
      worldId: 'growth',
      name: 'Progressive',
      icon: '📈',
      description: 'Make consistent progress',
      rarity: 'uncommon',
      criteria: 'Track growth for 30 days',
    },
    {
      id: 'growth-transformer',
      worldId: 'growth',
      name: 'Transformer',
      icon: '⚡',
      description: 'Transform yourself',
      rarity: 'uncommon',
      criteria: 'Complete personal transformation',
    },
    {
      id: 'growth-evolving',
      worldId: 'growth',
      name: 'Evolving',
      icon: '🦋',
      description: 'Complete 10 growth entries',
      rarity: 'rare',
      criteria: 'Write 10 entries about growth',
    },
    {
      id: 'growth-metamorphosis',
      worldId: 'growth',
      name: 'Metamorphosis Master',
      icon: '🌸',
      description: 'Undergo profound change',
      rarity: 'rare',
      criteria: 'Transform your essence',
    },
    {
      id: 'growth-mastery-seeker',
      worldId: 'growth',
      name: 'Mastery Seeker',
      icon: '🎯',
      description: 'Pursue continuous mastery',
      rarity: 'epic',
      criteria: 'Achieve skill mastery',
    },
    {
      id: 'growth-quantum-leap',
      worldId: 'growth',
      name: 'Quantum Leap',
      icon: '🚀',
      description: 'Take exponential leaps',
      rarity: 'epic',
      criteria: 'Experience breakthrough growth',
    },
    {
      id: 'growth-enlightened-evolution',
      worldId: 'growth',
      name: 'Enlightened Evolution',
      icon: '✨',
      description: 'Evolve with consciousness',
      rarity: 'legendary',
      criteria: 'Integrate all growth lessons',
    },
    {
      id: 'growth-consciousness-expander',
      worldId: 'growth',
      name: 'Consciousness Expander',
      icon: '🌟',
      description: 'Expand consciousness',
      rarity: 'legendary',
      criteria: 'Reach higher awareness',
    },
    {
      id: 'growth-transcendent-becoming',
      worldId: 'growth',
      name: 'Transcendent Becoming',
      icon: '🙏',
      description: 'Transcend your limitations',
      rarity: 'mythic',
      criteria: 'Become your highest self',
    },
    {
      id: 'growth-cosmic-evolution',
      worldId: 'growth',
      name: 'Cosmic Evolution',
      icon: '🌌',
      description: 'Evolve with the universe',
      rarity: 'mythic',
      criteria: 'Reach cosmic potential',
    },
  ],
  decision: [
    {
      id: 'decision-maker',
      worldId: 'decision',
      name: 'Decision Maker',
      icon: '⚖️',
      description: 'Track your first decision',
      rarity: 'common',
      criteria: 'Log 1 decision',
    },
    {
      id: 'decision-clarifier',
      worldId: 'decision',
      name: 'Clarity Seeker',
      icon: '🔍',
      description: 'Gain clarity in decisions',
      rarity: 'common',
      criteria: 'Clarify 3 decisions',
    },
    {
      id: 'decision-wise',
      worldId: 'decision',
      name: 'Wise Decider',
      icon: '🧙',
      description: 'Make 10 aligned decisions',
      rarity: 'uncommon',
      criteria: 'Track 10 decisions',
    },
    {
      id: 'decision-intuitive',
      worldId: 'decision',
      name: 'Intuitive Decider',
      icon: '💫',
      description: 'Trust your intuition',
      rarity: 'uncommon',
      criteria: 'Follow intuitive guidance',
    },
    {
      id: 'decision-aligned',
      worldId: 'decision',
      name: 'Aligned Decider',
      icon: '✨',
      description: 'Make values-aligned choices',
      rarity: 'rare',
      criteria: 'Make 5 aligned decisions',
    },
    {
      id: 'decision-courageous',
      worldId: 'decision',
      name: 'Courageous Decider',
      icon: '🦁',
      description: 'Make brave decisions',
      rarity: 'rare',
      criteria: 'Take courageous action',
    },
    {
      id: 'decision-master',
      worldId: 'decision',
      name: 'Decision Master',
      icon: '👑',
      description: 'Master decision-making',
      rarity: 'epic',
      criteria: 'Achieve decision excellence',
    },
    {
      id: 'decision-flow',
      worldId: 'decision',
      name: 'Flow State Decider',
      icon: '🌊',
      description: 'Decide from flow state',
      rarity: 'epic',
      criteria: 'Act from alignment',
    },
    {
      id: 'decision-enlightened',
      worldId: 'decision',
      name: 'Enlightened Decider',
      icon: '🌟',
      description: 'Make conscious choices',
      rarity: 'legendary',
      criteria: 'Achieve decision wisdom',
    },
    {
      id: 'decision-oracle',
      worldId: 'decision',
      name: 'Oracle',
      icon: '🔮',
      description: 'Perceive future outcomes',
      rarity: 'legendary',
      criteria: 'See beyond the present',
    },
    {
      id: 'decision-destiny',
      worldId: 'decision',
      name: 'Destiny Decider',
      icon: '⚡',
      description: 'Shape your destiny through choices',
      rarity: 'mythic',
      criteria: 'Align with life purpose',
    },
    {
      id: 'decision-cosmic',
      worldId: 'decision',
      name: 'Cosmic Alignment',
      icon: '🌌',
      description: 'Decide in cosmic harmony',
      rarity: 'mythic',
      criteria: 'Act as universe',
    },
  ],
  purpose: [
    {
      id: 'purpose-seeker',
      worldId: 'purpose',
      name: 'Purpose Seeker',
      icon: '🔍',
      description: 'Begin your purpose journey',
      rarity: 'common',
      criteria: 'Journal about purpose',
    },
    {
      id: 'purpose-discoverer',
      worldId: 'purpose',
      name: 'Purpose Discoverer',
      icon: '🗺️',
      description: 'Uncover your true calling',
      rarity: 'common',
      criteria: 'Explore your passions',
    },
    {
      id: 'purpose-claimer',
      worldId: 'purpose',
      name: 'Purpose Claimer',
      icon: '🎯',
      description: 'Claim your purpose',
      rarity: 'uncommon',
      criteria: 'State your mission',
    },
    {
      id: 'purpose-devotee',
      worldId: 'purpose',
      name: 'Purpose Devotee',
      icon: '🙏',
      description: 'Dedicate to your calling',
      rarity: 'uncommon',
      criteria: 'Commit to your purpose',
    },
    {
      id: 'purpose-founder',
      worldId: 'purpose',
      name: 'Purpose Founder',
      icon: '🏔️',
      description: 'Define your life mission',
      rarity: 'rare',
      criteria: 'Complete purpose self-discovery',
    },
    {
      id: 'purpose-aligned-living',
      worldId: 'purpose',
      name: 'Aligned Living',
      icon: '✨',
      description: 'Live your purpose daily',
      rarity: 'rare',
      criteria: 'Act on your mission',
    },
    {
      id: 'purpose-fulfiller',
      worldId: 'purpose',
      name: 'Purpose Fulfiller',
      icon: '🌟',
      description: 'Fulfill your life mission',
      rarity: 'epic',
      criteria: 'Achieve your calling',
    },
    {
      id: 'purpose-master',
      worldId: 'purpose',
      name: 'Purpose Master',
      icon: '👑',
      description: 'Master your life purpose',
      rarity: 'epic',
      criteria: 'Perfect your calling',
    },
    {
      id: 'purpose-cosmic-calling',
      worldId: 'purpose',
      name: 'Cosmic Calling',
      icon: '🌌',
      description: 'Answer universal calling',
      rarity: 'legendary',
      criteria: 'Serve humanity',
    },
    {
      id: 'purpose-enlightened-mission',
      worldId: 'purpose',
      name: 'Enlightened Mission',
      icon: '💫',
      description: 'Embody enlightened purpose',
      rarity: 'legendary',
      criteria: 'Transform through purpose',
    },
    {
      id: 'purpose-destiny-incarnate',
      worldId: 'purpose',
      name: 'Destiny Incarnate',
      icon: '⚡',
      description: 'Become your destiny',
      rarity: 'mythic',
      criteria: 'Fully express your essence',
    },
    {
      id: 'purpose-universal-service',
      worldId: 'purpose',
      name: 'Universal Service',
      icon: '🕉️',
      description: 'Serve all of existence',
      rarity: 'mythic',
      criteria: 'Transcend personal purpose',
    },
  ],
  wellbeing: [
    {
      id: 'wellbeing-guardian',
      worldId: 'wellbeing',
      name: 'Wellbeing Guardian',
      icon: '🛡️',
      description: 'Commit to health practices',
      rarity: 'common',
      criteria: 'Journal about wellness once',
    },
    {
      id: 'wellbeing-healer',
      worldId: 'wellbeing',
      name: 'Inner Healer',
      icon: '🩹',
      description: 'Heal body and mind',
      rarity: 'common',
      criteria: 'Practice healing modalities',
    },
    {
      id: 'wellbeing-vitality',
      worldId: 'wellbeing',
      name: 'Vitality Champion',
      icon: '⚡',
      description: 'Maintain wellness for 30 days',
      rarity: 'uncommon',
      criteria: 'Log wellness activities for 1 month',
    },
    {
      id: 'wellbeing-balanced',
      worldId: 'wellbeing',
      name: 'Balanced Being',
      icon: '☯️',
      description: 'Balance all wellness dimensions',
      rarity: 'uncommon',
      criteria: 'Nurture body-mind-spirit',
    },
    {
      id: 'wellbeing-radiant',
      worldId: 'wellbeing',
      name: 'Radiant Being',
      icon: '✨',
      description: 'Radiate health and vitality',
      rarity: 'rare',
      criteria: 'Achieve radiant presence',
    },
    {
      id: 'wellbeing-harmony-keeper',
      worldId: 'wellbeing',
      name: 'Harmony Keeper',
      icon: '🎼',
      description: 'Maintain health harmony',
      rarity: 'rare',
      criteria: 'Keep wellness in balance',
    },
    {
      id: 'wellbeing-whole-self',
      worldId: 'wellbeing',
      name: 'Whole Self',
      icon: '🌱',
      description: 'Integrate all wellness aspects',
      rarity: 'epic',
      criteria: 'Achieve holistic health',
    },
    {
      id: 'wellbeing-vitality-master',
      worldId: 'wellbeing',
      name: 'Vitality Master',
      icon: '💪',
      description: 'Master vital energy',
      rarity: 'epic',
      criteria: 'Perfect your wellness',
    },
    {
      id: 'wellbeing-transcendent-health',
      worldId: 'wellbeing',
      name: 'Transcendent Health',
      icon: '🌟',
      description: 'Transcend health limitations',
      rarity: 'legendary',
      criteria: 'Achieve supreme wellness',
    },
    {
      id: 'wellbeing-embodied-wellness',
      worldId: 'wellbeing',
      name: 'Embodied Wellness',
      icon: '🧘',
      description: 'Embody perfect health',
      rarity: 'legendary',
      criteria: 'Live as wellness itself',
    },
    {
      id: 'wellbeing-divine-health',
      worldId: 'wellbeing',
      name: 'Divine Health',
      icon: '🙏',
      description: 'Connect to divine vitality',
      rarity: 'mythic',
      criteria: 'Access infinite health',
    },
    {
      id: 'wellbeing-enlightened-vitality',
      worldId: 'wellbeing',
      name: 'Enlightened Vitality',
      icon: '☀️',
      description: 'Embody enlightened wellness',
      rarity: 'mythic',
      criteria: 'Be radiant consciousness',
    },
  ],
  future: [
    {
      id: 'future-visionary',
      worldId: 'future',
      name: 'Visionary',
      icon: '🔮',
      description: 'Create your future vision',
      rarity: 'common',
      criteria: 'Journal about your future',
    },
    {
      id: 'future-dreamer',
      worldId: 'future',
      name: 'Future Dreamer',
      icon: '💭',
      description: 'Dream your ideal future',
      rarity: 'common',
      criteria: 'Envision possibilities',
    },
    {
      id: 'future-architect',
      worldId: 'future',
      name: 'Architect',
      icon: '🏗️',
      description: 'Plan 5-year goals',
      rarity: 'uncommon',
      criteria: 'Set long-term goals',
    },
    {
      id: 'future-builder',
      worldId: 'future',
      name: 'Future Builder',
      icon: '🔨',
      description: 'Build your future',
      rarity: 'uncommon',
      criteria: 'Take action on goals',
    },
    {
      id: 'future-manifestor',
      worldId: 'future',
      name: 'Manifestor',
      icon: '✨',
      description: 'Manifest desired reality',
      rarity: 'rare',
      criteria: 'Create through intention',
    },
    {
      id: 'future-creator',
      worldId: 'future',
      name: 'Reality Creator',
      icon: '🎨',
      description: 'Create your reality',
      rarity: 'rare',
      criteria: 'Sculpt your future',
    },
    {
      id: 'future-reality-shaper',
      worldId: 'future',
      name: 'Reality Shaper',
      icon: '⚡',
      description: 'Shape reality itself',
      rarity: 'epic',
      criteria: 'Manifest powerfully',
    },
    {
      id: 'future-destiny-designer',
      worldId: 'future',
      name: 'Destiny Designer',
      icon: '🎯',
      description: 'Design your destiny',
      rarity: 'epic',
      criteria: 'Create intentionally',
    },
    {
      id: 'future-cosmic-architect',
      worldId: 'future',
      name: 'Cosmic Architect',
      icon: '🌌',
      description: 'Architect cosmic future',
      rarity: 'legendary',
      criteria: 'Co-create with universe',
    },
    {
      id: 'future-timeline-master',
      worldId: 'future',
      name: 'Timeline Master',
      icon: '⏳',
      description: 'Master time and destiny',
      rarity: 'legendary',
      criteria: 'Navigate timelines',
    },
    {
      id: 'future-enlightened-creator',
      worldId: 'future',
      name: 'Enlightened Creator',
      icon: '🌟',
      description: 'Create from enlightenment',
      rarity: 'mythic',
      criteria: 'Manifest from higher self',
    },
    {
      id: 'future-infinite-potential',
      worldId: 'future',
      name: 'Infinite Potential',
      icon: '∞',
      description: 'Embody infinite possibility',
      rarity: 'mythic',
      criteria: 'Access all possibilities',
    },
  ],
};

/**
 * Get badges for a specific world
 */
export function getWorldBadges(worldId: WorldId): Badge[] {
  return WORLD_BADGES[worldId] || [];
}

/**
 * Calculate achievement points from badges
 */
export function calculateWorldPoints(worldId: WorldId, unlockedBadges: string[]): number {
  const badges = getWorldBadges(worldId);
  const rarityPoints: Record<BadgeRarity, number> = {
    common: 10,
    uncommon: 25,
    rare: 50,
    epic: 100,
    legendary: 250,
    mythic: 500,
  };

  return badges
    .filter((badge) => unlockedBadges.includes(badge.id))
    .reduce((sum, badge) => sum + rarityPoints[badge.rarity], 0);
}
