/**
 * AnalysisPage.tsx
 *
 * Full Personal Analysis — Route: /analysis
 *
 * Master Direction §10 — 9 sections:
 *   01 ภาพรวมตัวตน      02 รูปแบบพฤติกรรม   03 จุดแข็ง
 *   04 ข้อควรระวัง       05 แนวโน้ม           06 เส้นทางชีวิต
 *   07 สิ่งที่ควรสนใจ    08 ข้อแนะนำส่วนบุคคล  09 แผนพัฒนา
 *
 * Implementation:
 * - useAuth() for userId (never localStorage)
 * - useQuery — real Supabase data (shared cache keys with Dashboard)
 * - InsightEngine.generateFullAnalysis() — deterministic, real data
 * - No mocks, no hardcoding
 */

import React, { useMemo, useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useLangNavigate as useNavigate } from '../hooks/useLangNavigate';
import { useAuth } from '@/context/AuthContext';
import { useLifecycleStore } from '@/store/lifecycleStore';
import { PersonalContextBuilder } from '@/lib/intelligence/PersonalContextBuilder';
import { PatternDetector } from '@/lib/intelligence/PatternDetector';
import { AIFeedbackLoop } from '@/lib/intelligence/AIFeedbackLoop';
import { InsightEngine } from '@/lib/intelligence/InsightEngine';
import { ConfidenceIndicator } from '@/components/intelligence/ConfidenceIndicator';
import { NavBar } from '@/components/layout/NavBar';
import { Footer } from '@/components/layout/Footer';
import { BottomNav } from '@/components/layout/BottomNav';
import { NavRail } from '@/components/layout/NavRail';
import { Alert } from '@/components/composites/Alert';
import { useAnalysisStore } from '@/store/analysisStore';
import { useLanguage } from '@/context/LanguageContext';
import { supabase } from '@/services/supabase-service';
import { useVoiceTwin } from '@/hooks/useVoiceTwin';
import { WORLDS } from '@/constants/worlds';
import type { WorldId } from '@/constants/worlds';
import type { SICEOutput } from '@/types/sice';
import '../styles/analysis.css';

// ============================================================================
// Helpers — SICE world mapping
// ============================================================================

const ENGINE_TO_WORLD: Record<number, WorldId> = {
  1: 'self', 2: 'mind', 3: 'relationship', 4: 'love',
  5: 'career', 6: 'wealth', 7: 'life', 8: 'growth',
  9: 'decision', 10: 'purpose', 11: 'wellbeing', 12: 'future',
};

/** Extract a human-readable string from a SICEOutput result (unknown shape). */
function extractResultText(result: unknown): string {
  if (!result) return '';
  if (typeof result === 'string') return result;
  if (typeof result === 'object') {
    const r = result as Record<string, unknown>;
    for (const key of ['description', 'summary', 'text', 'insight', 'content', 'message', 'output', 'analysis']) {
      if (typeof r[key] === 'string' && r[key]) return r[key] as string;
    }
    for (const val of Object.values(r)) {
      if (typeof val === 'string' && val.length > 10) return val;
    }
  }
  return '';
}

// i18n scope note: displayAnalysis text (selfOverview, pattern names/
// descriptions, strengths, blindSpots, trends, journey, guidance, nextSteps)
// is generated by InsightEngine/PersonalContext — engine-sourced Thai
// content, same data-layer gap already flagged elsewhere (WorldDetail.tsx
// etc). Only this page's static UI chrome is made bilingual here.

// ============================================================================
// Section header helper
// ============================================================================

// APPSHELL-003 FIX: 9 sections used to render fully expanded at once —
// reading like a generated report, not a self-discovery experience. Each
// header is now a toggle; only the sections in `expandedSections` render
// their body (see .analysis__section--collapsed in analysis.css). Content
// and data-fetching are untouched — presentation layer only.
const SectionHeader: React.FC<{
  number: string;
  title: string;
  icon: string;
  isOpen: boolean;
  onToggle: () => void;
}> = ({ number, title, icon, isOpen, onToggle }) => (
  <button
    type="button"
    className="analysis__section-header"
    onClick={onToggle}
    aria-expanded={isOpen}
  >
    <span className="analysis__section-number">{number}</span>
    <span className="analysis__section-icon" aria-hidden="true">{icon}</span>
    <h2 className="analysis__section-title">{title}</h2>
    <span className="analysis__section-chevron" aria-hidden="true">{isOpen ? '▾' : '▸'}</span>
  </button>
);

// ============================================================================
// Main Page
// ============================================================================

const AnalysisPage: React.FC = () => {
  const { session } = useAuth();
  const userId = session?.user?.id ?? '';
  const navigate = useNavigate();
  const { language } = useLanguage();
  const isTh = language === 'th';
  const setAnalysis = useAnalysisStore((state) => state.setAnalysis);
  const transitionTo = useLifecycleStore((state) => state.transitionTo);

  // APPSHELL-003 FIX: progressive disclosure — only "01 Self Overview" (the
  // quick-insight section) opens by default; the rest expand on tap instead
  // of dumping all 9 sections at once.
  const [expandedSections, setExpandedSections] = useState<Set<string>>(() => new Set(['01']));
  const toggleSection = (id: string) => {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  // Stable instances
  const contextBuilder = useMemo(() => new PersonalContextBuilder(), []);
  const patternDetector = useMemo(() => new PatternDetector(), []);
  const feedbackLoop = useMemo(() => new AIFeedbackLoop(), []);
  const insightEngine = useMemo(() => new InsightEngine(), []);

  // --------------------------------------------------------------------------
  // Queries — reuse dashboard cache keys → no extra Supabase calls
  // --------------------------------------------------------------------------

  const {
    data: context,
    isLoading: ctxLoading,
    error: ctxError,
  } = useQuery({
    queryKey: ['personalContext', userId],
    queryFn: () => contextBuilder.getContext(userId),
    enabled: !!userId,
    staleTime: 30_000,
  });

  const { data: patterns = [], isLoading: patLoading } = useQuery({
    queryKey: ['behavioralPatterns', userId],
    queryFn: () => patternDetector.detectPatterns(userId),
    enabled: !!userId,
    staleTime: 60_000,
  });

  const { data: metrics } = useQuery({
    queryKey: ['accuracyMetrics', userId],
    queryFn: () => feedbackLoop.getAccuracyMetrics(userId),
    enabled: !!userId,
    staleTime: 30_000,
  });

  // --------------------------------------------------------------------------
  // Full analysis (only when data is ready)
  // --------------------------------------------------------------------------

  const analysis = useMemo(() => {
    if (!context || context.sourceCount === 0) return null;
    return insightEngine.generateFullAnalysis(context, patterns, metrics ?? null);
  }, [context, patterns, metrics, insightEngine]);

  // PRIMARY data source: awakening_essence.sice_results (real SICE output).
  // Always fetched on page load — personal_context (InsightEngine path) is
  // now the fallback, not the primary. Raw sice_results + synthesis are
  // included in the return value so the 12 world cards can render them directly.
  const { data: essenceAnalysis } = useQuery({
    queryKey: ['awakeningEssence', userId],
    queryFn: async () => {
      if (!supabase) return null;
      const { data, error } = await supabase
        .from('awakening_essence')
        .select('personal_intelligence, sice_results, synthesis')
        .eq('user_id', userId)
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle();
      if (error || !data?.personal_intelligence) return null;
      const pi = data.personal_intelligence as {
        userUnderstanding?: number;
        recommendedAction?: string;
        confidence?: number;
        insights?: string[];
        nextStepsSuggested?: string[];
        warningsOrCautions?: string[];
      };
      const synth = (data.synthesis ?? {}) as {
        themes?: string[];
        agreements?: string[];
        confidenceScore?: number;
      };
      const siceArr: SICEOutput[] = Array.isArray(data.sice_results) ? (data.sice_results as SICEOutput[]) : [];
      const allInsights = pi.insights ?? [];
      return {
        // FullAnalysisOutput-compatible fields (used by existing 9 sections)
        selfOverview: [pi.recommendedAction, ...allInsights].filter(Boolean).join(' '),
        behavioralPatterns: [] as any[],
        strengths: (synth.themes ?? []).map((t: string, i: number) => ({
          name: t,
          description: allInsights[i] ?? allInsights[i % Math.max(allInsights.length, 1)] ?? t,
          confidence: (pi.confidence ?? 70) / 100,
          evidence: [] as string[],
        })),
        blindSpots: (pi.warningsOrCautions ?? []).map((w: string) => ({
          title: w, description: w, sensitivity: 'medium', confidence: 0.65,
        })),
        trends: [] as any[],
        journey: {
          currentStage: 'awakening',
          description: pi.recommendedAction ?? '',
          growing: (synth.agreements ?? []).slice(0, 2),
          changing: [] as string[],
          stillWorking: [] as string[],
        },
        focusAreas: allInsights.slice(0, 3),
        guidance: allInsights,
        nextSteps: pi.nextStepsSuggested ?? [],
        generatedAt: new Date(),
        modelAccuracy: (pi.confidence ?? 70) / 100,
        sourceCount: siceArr.length > 0 ? siceArr.length : 12,
        // Raw data for summary section and 12 world cards
        _siceResults: siceArr,
        _pi: pi,
        _synth: synth,
      };
    },
    enabled: !!userId,  // always fetch — sice_results is primary source
    staleTime: 60_000,
    retry: false,
  });

  // essenceAnalysis (sice_results) is PRIMARY; InsightEngine analysis is fallback
  const displayAnalysis = essenceAnalysis ?? analysis ?? null;

  // Write to analysisStore on page load so Twin (CoreAwakening) always has data —
  // previously only happened on "Awaken" button click, leaving the store empty
  // if the user navigated away and came back.
  useEffect(() => {
    if (displayAnalysis) {
      setAnalysis(displayAnalysis as any);
    }
  }, [displayAnalysis, setAnalysis]);

  const isLoading = ctxLoading || patLoading;

  // --------------------------------------------------------------------------
  // FULLANALYSIS-001: play the full analysis as speech.
  // Reuses useVoiceTwin (Web Speech API) — same hook already used in
  // CoreAwakening.tsx, no new dependency. Builds one flowing narrative
  // paragraph from every real section of displayAnalysis (not a bullet-point
  // read-out), so it reads like someone explaining the analysis out loud.
  // TTSLANG-001 FIX: was hardcoded to 'th-TH' regardless of site language —
  // spokenNarrative below is already correctly bilingual (isTh throughout),
  // so on /en/analysis this spoke English text with a Thai voice/lang tag,
  // an obvious mismatch. Language now follows the page, same as the text.
  // --------------------------------------------------------------------------

  const { state: voiceState, speak, stopSpeaking } = useVoiceTwin({ language: isTh ? 'th-TH' : 'en-US' });

  const spokenNarrative = useMemo(() => {
    if (!displayAnalysis) return '';
    const parts: string[] = [];
    if (displayAnalysis.selfOverview) parts.push(displayAnalysis.selfOverview);
    if (displayAnalysis.strengths.length > 0) {
      parts.push(
        (isTh ? 'จุดแข็งของคุณคือ ' : 'Your strengths are ') +
          displayAnalysis.strengths.map((s: { name: string }) => s.name).join(isTh ? ', ' : ', ') + '.'
      );
    }
    if (displayAnalysis.blindSpots.length > 0) {
      parts.push(
        (isTh ? 'สิ่งที่ควรระวังคือ ' : 'Things worth watching for: ') +
          displayAnalysis.blindSpots.map((b: { title: string }) => b.title).join(isTh ? ', ' : ', ') + '.'
      );
    }
    if (displayAnalysis.guidance.length > 0) {
      parts.push((isTh ? 'คำแนะนำสำหรับคุณ: ' : 'Guidance for you: ') + displayAnalysis.guidance.join(' '));
    }
    if (displayAnalysis.nextSteps.length > 0) {
      parts.push((isTh ? 'ก้าวต่อไปที่แนะนำ: ' : 'Recommended next steps: ') + displayAnalysis.nextSteps.join(' '));
    }
    return parts.join(' ');
  }, [displayAnalysis, isTh]);

  const isSpeaking = voiceState.mode === 'speaking';
  const handleTogglePlay = () => {
    if (isSpeaking) {
      stopSpeaking();
    } else if (spokenNarrative) {
      speak(spokenNarrative);
    }
  };

  // --------------------------------------------------------------------------
  // Redirect unauthenticated users — /analysis requires auth
  // --------------------------------------------------------------------------

  // Must come before early-return guards to satisfy React's Rules of Hooks
  React.useEffect(() => {
    if (!userId) {
      navigate('/onboarding', { replace: true });
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // --------------------------------------------------------------------------
  // Handlers
  // --------------------------------------------------------------------------

  const handleAwakeTwin = async () => {
    if (displayAnalysis && userId) {
      // Save analysis to store for CoreAwakening to use
      setAnalysis(displayAnalysis as any);
      // P0 FIX: Advance lifecycle ANALYSIS → AWAKENING (Twin birth ceremony)
      await transitionTo(userId, 'AWAKENING');
      // Navigate to Twin birth ceremony
      navigate('/core-awakening');
    }
  };

  // --------------------------------------------------------------------------
  // Guards
  // --------------------------------------------------------------------------

  if (!userId) {
    // useEffect above is already redirecting to /onboarding — show nothing
    return null;
  }

  // --------------------------------------------------------------------------
  // Render
  // --------------------------------------------------------------------------

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <NavBar />

      <main className="analysis__page">
        {/* Page header */}
        <div className="analysis__page-header">
          <button
            className="analysis__back-btn"
            onClick={() => navigate('/dashboard')}
            aria-label={isTh ? 'กลับไปหน้าหลัก' : 'Back to Dashboard'}
          >
            {isTh ? '← หน้าหลัก' : '← Dashboard'}
          </button>
          <div>
            <h1 className="analysis__page-title">{isTh ? 'การวิเคราะห์ส่วนตัวของคุณ' : 'Your personal analysis'}</h1>
            <p className="analysis__page-subtitle">
              {isTh
                ? 'ภาพรวมเต็มรูปแบบจาก AI ฝาแฝด — อ้างอิงข้อมูลจริงจากการใช้งานของคุณ'
                : 'A full picture from your AI twin — grounded in your real usage data'}
            </p>
          </div>
          {/* FULLANALYSIS-001: play the whole analysis aloud (th-TH TTS via
              useVoiceTwin — same engine as CoreAwakening's Twin voice).
              Only rendered when there's real narrative text to read and the
              browser supports speech synthesis. */}
          {displayAnalysis && spokenNarrative && voiceState.supported && (
            <button
              type="button"
              className="analysis__play-audio-btn"
              onClick={handleTogglePlay}
              aria-label={isTh ? (isSpeaking ? 'หยุดเล่นเสียง' : 'ฟังผลวิเคราะห์') : (isSpeaking ? 'Stop' : 'Play analysis')}
            >
              {isSpeaking ? '⏹ ' + (isTh ? 'หยุด' : 'Stop') : '🔊 ' + (isTh ? 'ฟังผลวิเคราะห์' : 'Play analysis')}
            </button>
          )}
          {metrics && metrics.totalInsights > 0 && (
            <div className="analysis__header-confidence">
              <ConfidenceIndicator
                confidence={metrics.accuracy}
                evidenceCount={metrics.totalInsights}
                compact
                explanation={isTh
                  ? `ฝาแฝด เข้าใจ ${Math.round(metrics.accuracy * 100)}% จาก ${metrics.totalInsights} feedbacks`
                  : `Your twin is ${Math.round(metrics.accuracy * 100)}% accurate from ${metrics.totalInsights} feedbacks`}
              />
            </div>
          )}
        </div>

        {/* Error */}
        {ctxError && (
          <Alert
            variant="error"
            message={isTh
              ? `ไม่สามารถโหลดข้อมูล: ${ctxError instanceof Error ? ctxError.message : String(ctxError)}`
              : `Failed to load data: ${ctxError instanceof Error ? ctxError.message : String(ctxError)}`}
          />
        )}

        {/* Loading */}
        {isLoading && (
          <div className="analysis__loading" aria-live="polite">
            <div className="analysis__spinner" aria-hidden="true" />
            <p>{isTh ? 'กำลังสังเคราะห์รูปแบบต้นแบบของคุณ...' : 'Synthesizing your blueprint...'}</p>
          </div>
        )}

        {/* No data */}
        {!isLoading && !displayAnalysis && (
          <div className="analysis__empty">
            <div className="analysis__empty-icon">🌱</div>
            <h2>{isTh ? 'ยังไม่มีข้อมูลเพียงพอ' : 'Not enough data yet'}</h2>
            <p>
              {isTh
                ? 'ใช้ Selfprint ต่อไปสักระยะ บันทึกความทรงจำและ reflection เพื่อให้ ฝาแฝด สร้างการวิเคราะห์ที่ชัดเจนขึ้น'
                : 'Keep using Selfprint a while longer — log memories and reflections so your twin can build a clearer analysis'}
            </p>
            <button className="analysis__back-btn" onClick={() => navigate('/dashboard')}>
              {isTh ? 'กลับไปบันทึกความทรงจำ' : 'Back to log a memory'}
            </button>
          </div>
        )}

        {/* Full analysis — sice_results primary, InsightEngine fallback */}
        {!isLoading && displayAnalysis && (
          <div className="analysis__content">

            {/* ── Top Summary ── astrology-style narrative from SICE synthesis */}
            {essenceAnalysis && (essenceAnalysis._pi.recommendedAction || (essenceAnalysis._pi.insights ?? []).length > 0) && (
              <section className="analysis__summary-section" aria-label={isTh ? 'ภาพรวมส่วนตัว' : 'Personal summary'}>
                <div className="analysis__summary-header">
                  <span className="analysis__summary-icon" aria-hidden="true">✨</span>
                  <h2 className="analysis__summary-title">
                    {isTh ? 'ภาพรวมส่วนตัวของคุณ' : 'Your Personal Overview'}
                  </h2>
                  {essenceAnalysis._synth.confidenceScore != null && (
                    <span className="analysis__summary-confidence">
                      {Math.round(essenceAnalysis._synth.confidenceScore)}% {isTh ? 'ความแม่นยำ' : 'confidence'}
                    </span>
                  )}
                </div>

                {essenceAnalysis._pi.recommendedAction && (
                  <p className="analysis__summary-lead">{essenceAnalysis._pi.recommendedAction}</p>
                )}

                {(essenceAnalysis._pi.insights ?? []).length > 0 && (
                  <div className="analysis__summary-insights">
                    {(essenceAnalysis._pi.insights ?? []).map((insight, i) => (
                      <p key={i} className="analysis__summary-insight">{insight}</p>
                    ))}
                  </div>
                )}

                {(essenceAnalysis._synth.themes ?? []).length > 0 && (
                  <div className="analysis__summary-themes">
                    <span className="analysis__summary-themes-label">
                      {isTh ? 'แก่นสำคัญ:' : 'Key themes:'}
                    </span>
                    <div className="analysis__summary-theme-tags">
                      {(essenceAnalysis._synth.themes ?? []).map((t, i) => (
                        <span key={i} className="analysis__theme-tag">{t}</span>
                      ))}
                    </div>
                  </div>
                )}

                {(essenceAnalysis._synth.agreements ?? []).length > 0 && (
                  <div className="analysis__summary-agreements">
                    <p className="analysis__summary-agreements-label">
                      {isTh ? 'สิ่งที่ SICE เห็นตรงกันทั้ง 12 มิติ:' : 'Patterns agreed across all 12 dimensions:'}
                    </p>
                    <ul className="analysis__summary-agreements-list">
                      {(essenceAnalysis._synth.agreements ?? []).map((a, i) => (
                        <li key={i}>{a}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {(essenceAnalysis._pi.nextStepsSuggested ?? []).length > 0 && (
                  <div className="analysis__summary-nextsteps">
                    <p className="analysis__summary-nextsteps-label">
                      {isTh ? 'ก้าวต่อไปที่แนะนำ:' : 'Recommended next steps:'}
                    </p>
                    <ol className="analysis__summary-nextsteps-list">
                      {(essenceAnalysis._pi.nextStepsSuggested ?? []).map((s, i) => (
                        <li key={i}>{s}</li>
                      ))}
                    </ol>
                  </div>
                )}
              </section>
            )}

            {/* ── 12 World Cards ── one per SICE engine */}
            {essenceAnalysis && essenceAnalysis._siceResults.length > 0 && (
              <section className="analysis__worlds-section" aria-label={isTh ? '12 มิติ SICE' : '12 SICE Dimensions'}>
                <div className="analysis__worlds-header">
                  <h2 className="analysis__worlds-title">
                    {isTh ? '12 มิติชีวิตของคุณ' : 'Your 12 Life Dimensions'}
                  </h2>
                  <p className="analysis__worlds-subtitle">
                    {isTh
                      ? 'ผลวิเคราะห์จาก SICE ทั้ง 12 เครื่องยนต์ปัญญาประดิษฐ์'
                      : 'Analysis from all 12 Specialized Intelligence Capability Engines'}
                  </p>
                </div>
                <div className="analysis__world-grid">
                  {essenceAnalysis._siceResults.map((r) => {
                    const worldId = ENGINE_TO_WORLD[r.engineId];
                    const world = worldId ? WORLDS[worldId] : null;
                    const text = extractResultText(r.result);
                    return (
                      <div
                        key={r.engineId}
                        className="analysis__world-card"
                        style={{ '--world-accent': world?.color ?? 'var(--accent-primary)' } as React.CSSProperties}
                      >
                        <div className="analysis__world-card-header">
                          <span className="analysis__world-card-emoji" aria-hidden="true">
                            {world?.emoji ?? '🌐'}
                          </span>
                          <div className="analysis__world-card-meta">
                            <span className="analysis__world-card-name">
                              {isTh ? (world?.nameTh ?? r.engineName) : (world?.name ?? r.engineName)}
                            </span>
                            {world && (
                              <span className="analysis__world-card-mood">
                                {isTh ? world.moodTh : world.mood}
                              </span>
                            )}
                          </div>
                          <span className="analysis__world-card-confidence">
                            {r.confidence}%
                          </span>
                        </div>
                        {text && (
                          <p className="analysis__world-card-text">{text}</p>
                        )}
                        {r.error && (
                          <p className="analysis__world-card-error">
                            {isTh ? 'ไม่สามารถวิเคราะห์มิตินี้ได้' : 'Could not analyse this dimension'}
                          </p>
                        )}
                      </div>
                    );
                  })}
                </div>
              </section>
            )}

            <div className="analysis__expand-all">
              <button
                type="button"
                className="analysis__expand-all-btn"
                onClick={() => setExpandedSections(new Set(['01', '02', '03', '04', '05', '06', '07', '08', '09']))}
              >
                {isTh ? 'ขยายทั้งหมด' : 'Expand all'}
              </button>
              <button
                type="button"
                className="analysis__expand-all-btn"
                onClick={() => setExpandedSections(new Set(['01']))}
              >
                {isTh ? 'ย่อทั้งหมด' : 'Collapse all'}
              </button>
            </div>

            {/* 01 — ภาพรวมตัวตน */}
            <section className={`analysis__section${expandedSections.has('01') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-01">
              <SectionHeader number="01" title={isTh ? 'ภาพรวมตัวตน' : 'Self Overview'} icon="🪞" isOpen={expandedSections.has('01')} onToggle={() => toggleSection('01')} />
              <div className="analysis__section-body">
                <p className="analysis__overview-text">{displayAnalysis.selfOverview}</p>
                {context && (
                  <div className="analysis__meta-row">
                    <span className="analysis__meta-item">
                      📊 {isTh ? `ข้อมูล ${displayAnalysis.sourceCount} ชิ้น` : `${displayAnalysis.sourceCount} data points`}
                    </span>
                    <span className="analysis__meta-item">
                      🗓 {isTh ? 'อัพเดต' : 'Updated'} {displayAnalysis.generatedAt.toLocaleDateString(isTh ? 'th-TH' : 'en-US')}
                    </span>
                    {displayAnalysis.modelAccuracy > 0 && (
                      <span className="analysis__meta-item">
                        🎯 {isTh ? 'เข้าใจ' : 'Understanding'} {Math.round(displayAnalysis.modelAccuracy * 100)}%
                      </span>
                    )}
                  </div>
                )}
              </div>
            </section>

            {/* 02 — รูปแบบพฤติกรรม */}
            <section className={`analysis__section${expandedSections.has('02') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-02">
              <SectionHeader number="02" title={isTh ? 'รูปแบบพฤติกรรม' : 'Behavioral Patterns'} icon="📊" isOpen={expandedSections.has('02')} onToggle={() => toggleSection('02')} />
              <div className="analysis__section-body">
                {displayAnalysis.behavioralPatterns.length === 0 ? (
                  <p className="analysis__empty-section">
                    {isTh
                      ? 'ยังไม่พบรูปแบบที่ชัดเจน — ใช้งานต่อไปเพื่อให้ ฝาแฝด สังเกตรูปแบบที่ชัดเจนของคุณมากขึ้น'
                      : 'No clear patterns yet — keep using Selfprint so your twin can notice clearer patterns'}
                  </p>
                ) : (
                  <div className="analysis__pattern-list">
                    {displayAnalysis.behavioralPatterns.map((p, i) => (
                      <div key={i} className="analysis__pattern-item">
                        <div className="analysis__pattern-item-header">
                          <div>
                            <span className="analysis__pattern-type-badge">
                              {isTh
                                ? (p.type === 'repeating' ? '🔁 ซ้ำ' : p.type === 'emerging' ? '🌱 เกิดขึ้นใหม่' : '🔄 เปลี่ยนแปลง')
                                : (p.type === 'repeating' ? '🔁 Repeating' : p.type === 'emerging' ? '🌱 Emerging' : '🔄 Changing')}
                            </span>
                            <h3 className="analysis__pattern-name">{p.name}</h3>
                          </div>
                          <ConfidenceIndicator confidence={p.confidence} compact />
                        </div>
                        <p className="analysis__pattern-desc">{p.description}</p>
                        {p.insight && (
                          <p className="analysis__pattern-insight">💡 {p.insight}</p>
                        )}
                        <p className="analysis__pattern-freq">
                          {isTh ? 'ความถี่' : 'Frequency'}: {p.frequency} · {isTh ? 'พบล่าสุด' : 'Last seen'}{' '}
                          {p.lastDetected.toLocaleDateString(isTh ? 'th-TH' : 'en-US')}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>

            {/* 03 — จุดแข็ง */}
            <section className={`analysis__section${expandedSections.has('03') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-03">
              <SectionHeader number="03" title={isTh ? 'จุดแข็ง' : 'Strengths'} icon="💪" isOpen={expandedSections.has('03')} onToggle={() => toggleSection('03')} />
              <div className="analysis__section-body">
                {displayAnalysis.strengths.length === 0 ? (
                  <p className="analysis__empty-section">
                    {isTh
                      ? 'ฝาแฝด ยังไม่ได้ระบุจุดแข็งของคุณ — ใช้ Selfprint ต่อไปเพื่อให้ข้อมูลมากขึ้น'
                      : "Your twin hasn't identified your strengths yet — keep using Selfprint to provide more data"}
                  </p>
                ) : (
                  <div className="analysis__strength-grid">
                    {displayAnalysis.strengths.map((s, i) => (
                      <div key={i} className="analysis__strength-card">
                        <div className="analysis__strength-header">
                          <h3 className="analysis__strength-name">{s.name}</h3>
                          <ConfidenceIndicator confidence={s.confidence} compact />
                        </div>
                        {s.description && (
                          <p className="analysis__strength-desc">{s.description}</p>
                        )}
                        {s.evidence.length > 0 && (
                          <p className="analysis__strength-evidence">
                            {isTh ? `จาก ${s.evidence.length} หลักฐาน` : `From ${s.evidence.length} pieces of evidence`}
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>

            {/* 04 — ข้อควรระวัง */}
            <section className={`analysis__section${expandedSections.has('04') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-04">
              <SectionHeader number="04" title="Blind Spots" icon="🔍" isOpen={expandedSections.has('04')} onToggle={() => toggleSection('04')} />
              <div className="analysis__section-body">
                <p className="analysis__section-note">
                  {isTh
                    ? 'สิ่งเหล่านี้คือสิ่งที่ ฝาแฝดคุณ สังเกตว่าคุณอาจมองข้ามไป — ไม่ใช่การตัดสิน แต่เป็นพื้นที่ให้สำรวจ'
                    : "These are things your twin has noticed you might be overlooking — not a judgment, just areas worth exploring"}
                </p>
                {displayAnalysis.blindSpots.length === 0 ? (
                  <p className="analysis__empty-section">
                    {isTh ? 'ยังไม่พบ ข้อควรระวัง ที่ชัดเจนในตอนนี้' : 'No clear blind spots found yet'}
                  </p>
                ) : (
                  <div className="analysis__blindspot-list">
                    {displayAnalysis.blindSpots.map((b, i) => (
                      <div key={i} className="analysis__blindspot-item">
                        <div className="analysis__blindspot-header">
                          <h3 className="analysis__blindspot-title">{b.title}</h3>
                          <ConfidenceIndicator confidence={b.confidence} compact />
                        </div>
                        {b.description && (
                          <p className="analysis__blindspot-desc">{b.description}</p>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>

            {/* 05 — แนวโน้ม */}
            <section className={`analysis__section${expandedSections.has('05') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-05">
              <SectionHeader number="05" title={isTh ? 'แนวโน้ม' : 'Trends'} icon="📈" isOpen={expandedSections.has('05')} onToggle={() => toggleSection('05')} />
              <div className="analysis__section-body">
                {displayAnalysis.trends.length === 0 ? (
                  <p className="analysis__empty-section">
                    {isTh ? 'ยังไม่มีแนวโน้มการเปลี่ยนแปลงที่ชัดเจน — กลับมาดูในอีก 30 วัน' : 'No clear trends yet — check back in 30 days'}
                  </p>
                ) : (
                  <div className="analysis__trend-list">
                    {displayAnalysis.trends.map((t, i) => (
                      <div key={i} className="analysis__trend-item">
                        <p className="analysis__trend-desc">{t.description}</p>
                        {t.insight && (
                          <p className="analysis__trend-insight">💡 {t.insight}</p>
                        )}
                        <p className="analysis__trend-since">
                          {isTh ? 'ตั้งแต่' : 'Since'} {t.since.toLocaleDateString(isTh ? 'th-TH' : 'en-US')} ·{' '}
                          <ConfidenceIndicator confidence={t.confidence} compact />
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>

            {/* 06 — เส้นทางชีวิต */}
            <section className={`analysis__section${expandedSections.has('06') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-06">
              <SectionHeader number="06" title="Journey" icon="🗺" isOpen={expandedSections.has('06')} onToggle={() => toggleSection('06')} />
              <div className="analysis__section-body">
                <div className="analysis__journey-stage">
                  <span className="analysis__journey-stage-label">{isTh ? 'ตอนนี้คุณอยู่ที่:' : 'Right now you are at:'}</span>
                  <span className="analysis__journey-stage-value">{displayAnalysis.journey.currentStage}</span>
                </div>
                <p className="analysis__journey-desc">{displayAnalysis.journey.description}</p>

                <div className="analysis__journey-grid">
                  {displayAnalysis.journey.growing.length > 0 && (
                    <div className="analysis__journey-col">
                      <h4 className="analysis__journey-col-title">🌱 {isTh ? 'สิ่งที่เติบโต' : 'Growing'}</h4>
                      <ul className="analysis__journey-list">
                        {displayAnalysis.journey.growing.map((g, i) => <li key={i}>{g}</li>)}
                      </ul>
                    </div>
                  )}
                  {displayAnalysis.journey.changing.length > 0 && (
                    <div className="analysis__journey-col">
                      <h4 className="analysis__journey-col-title">🔄 {isTh ? 'สิ่งที่เปลี่ยนแปลง' : 'Changing'}</h4>
                      <ul className="analysis__journey-list">
                        {displayAnalysis.journey.changing.map((c, i) => <li key={i}>{c}</li>)}
                      </ul>
                    </div>
                  )}
                  {displayAnalysis.journey.stillWorking.length > 0 && (
                    <div className="analysis__journey-col">
                      <h4 className="analysis__journey-col-title">⚙️ {isTh ? 'กำลังพัฒนา' : 'Still working on'}</h4>
                      <ul className="analysis__journey-list">
                        {displayAnalysis.journey.stillWorking.map((w, i) => <li key={i}>{w}</li>)}
                      </ul>
                    </div>
                  )}
                </div>
              </div>
            </section>

            {/* 07 — สิ่งที่ควรสนใจ */}
            <section className={`analysis__section${expandedSections.has('07') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-07">
              <SectionHeader number="07" title={isTh ? 'สิ่งที่ควรให้ความสนใจ' : 'Focus Areas'} icon="🎯" isOpen={expandedSections.has('07')} onToggle={() => toggleSection('07')} />
              <div className="analysis__section-body">
                {displayAnalysis.focusAreas.length === 0 ? (
                  <p className="analysis__empty-section">
                    {isTh ? 'ฝาแฝด ยังไม่สามารถระบุพื้นที่ที่ควรให้ความสนใจได้ชัดเจน' : "Your twin can't identify clear focus areas yet"}
                  </p>
                ) : (
                  <div className="analysis__focus-list">
                    {displayAnalysis.focusAreas.map((area, i) => (
                      <div key={i} className="analysis__focus-item">
                        <span className="analysis__focus-number">{i + 1}</span>
                        <span className="analysis__focus-text">{area}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>

            {/* 08 — ข้อแนะนำส่วนบุคคล */}
            <section className={`analysis__section${expandedSections.has('08') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-08">
              <SectionHeader number="08" title="Personal Guidance" icon="🧭" isOpen={expandedSections.has('08')} onToggle={() => toggleSection('08')} />
              <div className="analysis__section-body">
                <p className="analysis__section-note">
                  {isTh
                    ? 'คำแนะนำเหล่านี้มาจากรูปแบบที่ ฝาแฝด สังเกตเห็น — เป็นแค่คำถามให้คุณลองสำรวจ'
                    : "This guidance comes from patterns your twin has noticed — just questions worth exploring, not directives"}
                </p>
                {displayAnalysis.guidance.length === 0 ? (
                  <p className="analysis__empty-section">{isTh ? 'ยังไม่มีคำแนะนำเฉพาะบุคคลในตอนนี้' : 'No personal guidance yet'}</p>
                ) : (
                  <div className="analysis__guidance-list">
                    {displayAnalysis.guidance.map((g, i) => (
                      <div key={i} className="analysis__guidance-item">
                        <span className="analysis__guidance-bullet">→</span>
                        <p className="analysis__guidance-text">{g}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>

            {/* 09 — แผนพัฒนา */}
            <section className={`analysis__section analysis__section--last${expandedSections.has('09') ? '' : ' analysis__section--collapsed'}`} aria-labelledby="section-09">
              <SectionHeader number="09" title="Next Step" icon="🚀" isOpen={expandedSections.has('09')} onToggle={() => toggleSection('09')} />
              <div className="analysis__section-body">
                <div className="analysis__next-steps">
                  {displayAnalysis.nextSteps.map((step, i) => (
                    <div key={i} className="analysis__next-step">
                      <div className="analysis__next-step-num">{i + 1}</div>
                      <p className="analysis__next-step-text">{step}</p>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* Footer */}
            <div className="analysis__page-footer">
              <p className="analysis__disclaimer">
                {isTh
                  ? 'การวิเคราะห์นี้สร้างจากข้อมูลจริงที่ ฝาแฝดของคุณ เรียนรู้จากการใช้งานของคุณ ยิ่งใช้ Selfprint มาก ฝาแฝด ยิ่งเข้าใจคุณได้มากขึ้น'
                  : 'This analysis is built from real data your twin has learned from your usage. The more you use Selfprint, the better your twin understands you.'}
              </p>
              <div className="analysis__footer-buttons">
                <button
                  className="analysis__back-to-dashboard"
                  onClick={() => navigate('/dashboard')}
                >
                  {isTh ? '← กลับ Dashboard' : '← Back to Dashboard'}
                </button>
                {displayAnalysis && (
                  <button
                    className="analysis__awaken-twin-btn"
                    onClick={handleAwakeTwin}
                    aria-label={isTh ? 'ตื่นตัวฝาแฝดของคุณ' : 'Awaken your twin'}
                  >
                    {isTh ? '✨ ความรู้ของคุณพร้อมแล้ว → ตื่นตัวฝาแฝด' : '✨ Your knowledge is ready → Awaken your Twin'}
                  </button>
                )}
              </div>
            </div>

          </div>
        )}
      </main>

      <Footer />
      <NavRail />
      <BottomNav />
    </div>
  );
};

export default AnalysisPage;
